server:
  port: 8081  # Adjusted port to avoid conflicts
spring:
  00application:
   0 name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: http://user-service:8081
          predicates:
            - Path=/users/**
        - id: product-service-route
          uri: http://product-service:8082
          predicates:
            - Path=/products/**
  
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.153:8761/eureka/  

zuul:
  routes:  # Routes configuration (add specific route definitions)


custom:  # Create a section named 'custom' for your properties
  test: Hello from dev! 