server:
port: 8080

spring:
application:
name: users-service

logging:
level:
  root: INFO
  com.example.userservice: DEBUG



eureka:
client:
service-url:
defaultZone: http://localhost:8761/eureka/prod

zuul:
routes:
